version: '3'

x-omnistrate-integrations:
  - omnistrateLogging:
  - omnistrateMetrics:

x-omnistrate-service-plan:
  name: 'ray-cluster'
  tenancyType: 'OMNISTRATE_DEDICATED_TENANCY'
  deployment:
    byoaDeployment:
      AwsAccountId: '621523791457'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::621523791457:role/omnistrate-bootstrap-role'

services:
  serverless-framework:
    build:
      context: ./src
      dockerfile: Dockerfile

x-omnistrate-image-registry-attributes:
  ghcr.io:
    auth:
      password: ${{ secrets.GitHubPAT }}
      username: NolanJMcCafferty
